#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# Listens on port 80.
# Returns a page containing "Hello World!" when queried
# at the root with a curl GET request.

# Update apt package index
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create a file containing the "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
