#!/usr/bin/env bash
# install and configure ngix

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
