#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" > /var/www/sites-available/default

sudo service nginx restart
