#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html >/dev/null

SERVER_CONFIG=\
"server {
	\tlisten 80 default_server;
	\tlisten [::]:80 default_server;

	\troot /var/www/html;
	\tindex index.html index.htm index.nginx-debian.html;



}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

reflink="\\\tserver_name _;\n\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "8i$reflink" /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
