#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”


# Update apt package index
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx
sudo apt-get -y install ufw
sudo apt --fix-broken -y install

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
sudo service nginx start
# Create a file containing the "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html
printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;

    root        /var/www/html;
    index       index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
		try_files \$uri \$uri/ =404;
	}



}" > /etc/nginx/sites-available/default

sudo sed -i '14i\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
