#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”


# Update apt package index
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx
sudo apt-get -y install ufw
sudo apt --fix-broken -y install

sudo ufw allow 'Nginx HTTP'
sudo service nginx start
# Create a file containing the errror message
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;

    root        /var/www/html;
    index       index.html index.htm index.nginx-debian.html;

    server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}



}" > /etc/nginx/sites-available/default

sudo sed -i '14i\\terror_page 404 /404.html; \n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart

