#!/usr/bin/env bash
# set up custom error 404 page

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

echo 'Hello World!' | sudo tee /var/www/html/index.html >/dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html >/dev/null

SERVER_CONFIG=\
"server {
	\tlisten 80 default_server;
	\tlisten [::]:80 default_server;

	\troot /var/www/html;
	\tindex index.html index.htm index.nginx-debian.html;



}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

reflink1="\\\tserver_name _;\n\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
reflink2="\n\n\terror_page 404 /404.html; \n\tlocation = /404.html {\n\t\tinternal;\n\t}\n\n"
reflink="$reflink1 $reflink2"

sudo sed -i "8i$reflink" /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
