#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get install -y haproxy=2.5.\*

echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Listen to web1 and web2 servers
balancer="\
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 152184-web-01 100.26.222.79:80 check
   server 152184-web-02 100.26.222.79:80 check
"
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
haproxy -c -V -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
