#!/usr/bin/env bash
# config ngnix server to listen to port 80 short way
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /run/nginx.pid
